export const constituencies = {
  "Thiruvananthapuram": [
   "Varkala",	
   "Attingal",	
   "Chirayinkeezhu",
   "Nedumangad",
   "Vamanapuram",
   "Kazhakootam",	
   "Vattiyoorkavu",	
   "Thiruvananthapuram",
   "Nemom",
   "Aruvikkara",
   "Parassala",
   "Kattakkada",	
   "Kovalam",
   "Neyyattinkara"
  ],
  "Kollam": [
    "Karunagapally",
    "Chavara",
    "Kunnathur",
    "Kottarakkara",
    "Pathanapuram",
    "Punalur",
    "Chadayamangalam",
    "Kundara",
    "Kollam",
    "Eravipuram",
    "Chathannoor"
    ],
    "Pathanamthitta": [
      "Adoor",
      "Ranni",
      "Aranmula",
      "Konni",
      "Thiruvalla",
    ],
    "Alappuzha": [
    "Aroor",
	"Cherthala",
	"Alappuzha",
	"Ambalappuzha",
	"Kuttanad	",
	"Haripad",
	"Kayamkulam",
	"Mavelikara",
	"Chengannur"
    ],
    "Kottayam": [
      "Puthuppally",
      "Changanassery",
      "Kanjirappally",
      "Poonjar",
      "Pala",
      "Kottayam",
      "Kadathuruthy",
      "Vaikom",
      "Ettumanoor"
    ],
    "Idukki": [
      "Udumbanchola",
      "Thodupuzha",
      "Devikulam",
      "Idukki",
      "Peerumade",
    ],
    "Ernakulam": [
      "Perumbavoor",
      "Angamaly",
      "Aluva",
      "Muvattupuzha",
      "Kothamangalam",
      "Kalamassery",
      "Paravur",
      "Vypin",
      "Kochi",
      "Thrippunithura",
      "Ernakulam",
      "Thrikkakara",
      "Kunnathunad",
      "Piravom"
    ],
    "Thrissur": [
      "Chelakkara",
      "Kunnamkulam",
      "Guruvayoor",
      "Manalur",
      "Wadakkanchery",
      "Ollur",
      "Thrissur",
      "Nattika",
      "Kaipamangalam",
      "Irinjalakuda",
      "Puthukkad",
      "Chalakudy",
      "Kodungallur"
    ],
    "Palakkad": [
    "Thrithala",	
    "Pattambi",
    "Shornur",
    "Ottapalam",
    "Kongad (SC)",	
    "Mannarkkad",		
    "Malampuzha",	
    "Palakkad",		
    "Tarur",
    "Chittur",	
    "Nenmara",		
    "Alathur"
    ],
    "Malappuram": [
      "Kondotty",
      "Eranad",
      "Nilambur",
      "Wandoor",
      "Manjeri",
      "Perinthalmanna",
      "Mankada",
      "Malappuram",
      "Vengara",
      "Vallikunnu",
      "Tirurangadi",
      "Tanur",
      "Tirur",
      "Kottakkal",
      "Thavanur",
      "Ponani"
    ],
    "Kozhikode": [
      "Kuttiadi",
      "Vadakara",
      "Koyilandy",
      "Beypore",
      "Kozhikode North",
      "Kozhikode South",
      "Balussery",
      "Elathur",
      "Nadapuram",
      "Perambra",
      "Kunnamangalam",
      "Koduvally",
      "Thiruvambady"
    ],
    "Wayanad": [
      "Mananthavady",
      "Sulthan Bathery",
      "Kalpetta"
    ],
    "Kannur": [
      "Taliparamba",
      "Irikkur",
      "Azhikode",
      "Kannur",
      "Dharmadam",
      "Thalassery",
      "Kuthuparamba",
      "Mattannur",
      "Peravoor",
      "Payyannur",
      "Kalliasseri"
    ],
    "Kasaragod": [
      "Kasaragod",
      "Manjeshwaram",
      "Udma",
      "Kanhangad",
      "Thrikaripur",
    ]
  };

  export const districtList = [
    "Thiruvananthapuram",
    "Kollam",
    "Pathanamthitta",
    "Alappuzha",
    "Kottayam",
    "Idukki",
    "Ernakulam",
    "Thrissur",
    "Palakkad",
    "Malappuram",
    "Kozhikode",
    "Wayanad",
    "Kannur",
    "Kasaragod"
  ]